
spring.application.name=spring-restapi
spring.datasource.url=jdbc:postgresql://localhost:5432/saad
spring.datasource.username=postgres
spring.datasource.password=saad2015
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
jwt.secret=VGhpcyBpcyBhIHZlcnkgc2VjdXJlIHNlY3JldCBrZXkgZm9yIGp3dA==
file.upload-dir=./uploads/